version: '2'
services:
    trappist-app:
        image: trappist
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://trappist-postgresql:5432/trappist
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trappist-postgresql:
        extends:
            file: postgresql.yml
            service: trappist-postgresql
